# config/packages/security.yaml
security:
    password_hashers:
        App\Entity\Utilisateur:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: false
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                csrf_token_id: authenticate
                username_parameter: email
                password_parameter: password
                default_target_path: app_dashboard
                always_use_default_target_path: true # Redirect to the dashboard after login
            entry_point: form_login
            logout:
                path: app_logout
                target: app_dashboard
            # Optionally enable remember me
            # remember_me:
            #     secret:   '%kernel.secret%'
            #     lifetime: 604800 # 1 week in seconds
            #     path:     /
    

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout$, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # Added logout
        #- { path: ^/, roles: ROLE_USER }