services:
  db:
    image: mysql:8.0
    container_name: symfony_db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # Allow root with no password
      MYSQL_DATABASE: carpool_symfony
    ports:
      - "3307:3306"
    networks:
      dev:



  web:
    build: ./docker/php
    container_name: symfony_app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
      - dev

networks:
  dev:
