services:
  db:
    image: mysql:8.0.32
    container_name: symfony
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: carpool_symfony
      MYSQL_USER: nour
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    networks:
      dev:


  web:
    build: php
    container_name: symfony_app
    ports:
      - "8080:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ../:/var/www
    depends_on:
      - db
    networks:
      - dev

networks:
  dev:

